# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/copybot/copybot_job.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/copybot/copybot_job.proto\x12\x07\x63opybot\"\x8a\x01\n\nCopybotJob\x12\x14\n\x0cnotify_email\x18\x01 \x03(\t\x12\x12\n\ngroup_name\x18\x02 \x01(\t\x12\x1a\n\x12offset_hour_of_day\x18\x03 \x01(\x02\x12\x10\n\x08interval\x18\x04 \x01(\r\x12\x0f\n\x07timeout\x18\x05 \x01(\r\x12\x13\n\x0b\x63onfig_file\x18\x06 \x03(\t\"8\n\x0b\x43opybotJobs\x12)\n\x0c\x63opybot_jobs\x18\x01 \x03(\x0b\x32\x13.copybot.CopybotJobB3Z1go.chromium.org/chromiumos/infra/proto/go/copybotb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.copybot.copybot_job_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/infra/proto/go/copybot'
  _COPYBOTJOB._serialized_start=43
  _COPYBOTJOB._serialized_end=181
  _COPYBOTJOBS._serialized_start=183
  _COPYBOTJOBS._serialized_end=239
# @@protoc_insertion_point(module_scope)
