"""

@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class CopybotJob(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NOTIFY_EMAIL_FIELD_NUMBER: builtins.int
    GROUP_NAME_FIELD_NUMBER: builtins.int
    OFFSET_HOUR_OF_DAY_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    CONFIG_FILE_FIELD_NUMBER: builtins.int
    @property
    def notify_email(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ]: ...
    group_name: typing.Text
    offset_hour_of_day: builtins.float
    interval: builtins.int
    timeout: builtins.int
    @property
    def config_file(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ]: ...
    def __init__(
        self,
        *,
        notify_email: typing.Optional[typing.Iterable[typing.Text]] = ...,
        group_name: typing.Text = ...,
        offset_hour_of_day: builtins.float = ...,
        interval: builtins.int = ...,
        timeout: builtins.int = ...,
        config_file: typing.Optional[typing.Iterable[typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "config_file",
            b"config_file",
            "group_name",
            b"group_name",
            "interval",
            b"interval",
            "notify_email",
            b"notify_email",
            "offset_hour_of_day",
            b"offset_hour_of_day",
            "timeout",
            b"timeout",
        ],
    ) -> None: ...

global___CopybotJob = CopybotJob

class CopybotJobs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COPYBOT_JOBS_FIELD_NUMBER: builtins.int
    @property
    def copybot_jobs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___CopybotJob
    ]: ...
    def __init__(
        self,
        *,
        copybot_jobs: typing.Optional[
            typing.Iterable[global___CopybotJob]
        ] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal["copybot_jobs", b"copybot_jobs"],
    ) -> None: ...

global___CopybotJobs = CopybotJobs
